#!/bin/python3

from random import randint

player=input('rock(r),paper(p)orscissors(s)?')
if player == 'r':
  print('0', end=' ')
  
if player == 's':
  print('>8', end=' ')
  
if player == 'p':
  print('__',end=' ')
  
print('vs' , end=' ')
chosen=randint(1,3)

#print(chosen)

if chosen == 1: 
  computer = 'r'
  print('0')
  
elif chosen == 2:
  computer = 'p'
  print('__')
  
else:
  computer = 's'
  print('>8')
  
#print(computer)

if player == computer:
  print('DRAW!')
elif player == 'r' and computer == 's':
  print('player wins!')
elif player == 'r' and computer == 'p':
  print('computer wins!')
elif player == 'p' and computer == 'r':
  print('player wins!')
elif player == 'p' and computer == 's':
  print('computer wins!')
elif player == 's' and computer == 'p':
  print ('player wins!')
elif player == 's' and computer == 'r':
  print ('computer wins!')
