#!/usr/bin/env python3
from mcpi.minecraft import Minecraft
from mcpi import block
mc = Minecraft.create()

x, y, z = mc.player.getTilePos()
mc.setBlocks(x-100000000000000, y-1000000000000000, z-1, x+1, y-1, z+1, 46, 1)
